stages:
  - build
  - deploy

build:
  stage: build
  image: node:10
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
    - public
  only:
    - master

deploy:
  stage: deploy
  image: microsoft/azure-cli
  dependencies:
    - build
  script:
    - az storage blob delete-batch -s "\$web" --connection-string $AZ_STORAGE_CONNECTION_STRING
    - az storage blob upload-batch -d "\$web" -s dist --connection-string $AZ_STORAGE_CONNECTION_STRING
  only:
    - master
